name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README with experience days
        run: |
          START_DATE="2023-07-13"
          TODAY=$(date +%Y-%m-%d)
          DAYS=$(( ( $(date -d $TODAY +%s) - $(date -d $START_DATE +%s) ) / 86400 ))
          sed -i "s/{{chart_experience_days}}/$DAYS/" README.md

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update experience days"
          git push
