name: Days Counter
on:
  schedule:
    - cron: "0 12 * * *"  # Codziennie o 12:00 UTC
  workflow_dispatch:

jobs:
  update-days:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calculate days
        id: calculate_days
        run: |
          start_date="2023-07-13"
          current_date=$(date +%Y-%m-%d)
          days_diff=$(( ( $(date -d "$current_date" +%s) - $(date -d "$start_date" +%s) ) / 86400 ))
          echo "DAYS=$days_diff" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/<!-- days_counter -->[0-9]*<!-- days_counter -->/<!-- days_counter -->${{ env.DAYS }}<!-- days_counter -->/g" README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update days counter to ${{ env.DAYS }}"
