name: Days Counter
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # Codziennie o 12:00 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Calculate days
        id: calculate
        run: |
          start_timestamp=1689206400 # 2023-07-13 w Unix Time
          current_timestamp=$(date +%s)
          days=$(( (current_timestamp - start_timestamp) / 86400 ))
          echo "DAYS=$days" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/DAYS_SINCE_START:[0-9]*/DAYS_SINCE_START:${{ env.DAYS }}/g" README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update days counter to ${{ env.DAYS }}"
          branch: main
